# params.yaml
num_nodes: 100          # Jumlah node acak yang dihasilkan
connect_radius: 30      # Radius untuk menghubungkan node
start: [10, 10]         # Koordinat titik awal
goal: [90, 90]          # Koordinat titik tujuan
map_size: [100, 100]    # Ukuran peta (misalnya 100x100)
